"""empty message

Revision ID: 1a170a4a450c
Revises: ee7852fbc3b4
Create Date: 2022-07-14 01:53:20.952372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a170a4a450c'
down_revision = 'ee7852fbc3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_result', sa.Column('accuracy', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('train_result', 'accuracy')
    # ### end Alembic commands ###
