"""empty message

Revision ID: 8da9f6fde3ef
Revises: d024ddd9f935
Create Date: 2022-07-15 12:01:55.961467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da9f6fde3ef'
down_revision = 'd024ddd9f935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duval_triangle_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ch4', sa.Float(), nullable=False),
    sa.Column('c2h4', sa.Float(), nullable=False),
    sa.Column('c2h2', sa.Float(), nullable=False),
    sa.Column('cx', sa.Float(), nullable=False),
    sa.Column('cy', sa.Float(), nullable=False),
    sa.Column('faultClass', sa.String(length=10), nullable=False),
    sa.Column('faultClassDefinition', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duval_triangle_history')
    # ### end Alembic commands ###
