"""empty message

Revision ID: d367ec85bd59
Revises: 8da9f6fde3ef
Create Date: 2022-07-15 12:26:29.533069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd367ec85bd59'
down_revision = '8da9f6fde3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duval_triangle_history', sa.Column('userId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'duval_triangle_history', 'user', ['userId'], ['id'], ondelete='CASCADE')
    op.add_column('train_result', sa.Column('userId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'train_result', 'user', ['userId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'train_result', type_='foreignkey')
    op.drop_column('train_result', 'userId')
    op.drop_constraint(None, 'duval_triangle_history', type_='foreignkey')
    op.drop_column('duval_triangle_history', 'userId')
    # ### end Alembic commands ###
