"""empty message

Revision ID: ddf35a1722e0
Revises: d367ec85bd59
Create Date: 2022-07-20 03:41:36.941470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf35a1722e0'
down_revision = 'd367ec85bd59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duval_pentagon_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h2', sa.Float(), nullable=False),
    sa.Column('c2h6', sa.Float(), nullable=False),
    sa.Column('ch4', sa.Float(), nullable=False),
    sa.Column('c2h4', sa.Float(), nullable=False),
    sa.Column('c2h2', sa.Float(), nullable=False),
    sa.Column('cx', sa.Float(), nullable=False),
    sa.Column('cy', sa.Float(), nullable=False),
    sa.Column('faultClass', sa.String(length=10), nullable=False),
    sa.Column('faultClassDefinition', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duval_pentagon_history')
    # ### end Alembic commands ###
